### ISSUE TITLE
Apply flood-filling networks to mouselight data

### ISSUE THREAD

**Issue by tathey1** [neurodata/brainlit#120]
A popular neuron segmentation alg called flood filling networks was applied to segment neurons in EM data. Does it transfer to our two-photon microscopy well?

Paper [here](https://www.nature.com/articles/s41592-018-0049-4)

**Comment by alishakodibagkar** [comment]
I had an issue with accessing the full version of this paper - does it require Hopkins wifi?

**Comment by tathey1** [comment]
@alishakodibagkar You should be able to access via Sheridan Libraries Catalyst search engine if you search the article title

**Comment by tathey1** [comment]
done [here](https://github.com/neurodata/brainlit/blob/develop/experiments/ffn/brainlit_ffn.ipynb)
