### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by tathey1** [neurodata/brainlit#124]
[log.txt](https://github.com/neurodata/brainlit/files/5197930/log.txt)
When I set up a virtual environment and pip install -e . on the default branch (deploy), I get an error in installing the dependencies (attached is the log file).

Afterwards, if I go into a python command line and type "import brainlit," I get an error that numpy is not installed, seems like none of the dependencies installed.

I am using Windows.

**Comment by shreyasingh1** [comment]
[
[log.txt](https://github.com/neurodata/brainlit/files/5203595/log.txt)
](url)

I received the same error message when setting up an anaconda virtual environment and doing python -m pip install -e . using python3.8.5 or any python 3.8+. Log file is attached.  
Switching to python3.7 removed this error message for me. I am also using Windows.

I ran the same command on a WSL2 Ubuntu Subsystem using Python3.8 and didn't receive an error.

**Comment by bvarjavand** [comment]
While I created a python3.7-compatible [branch](https://github.com/neurodata/brainlit/tree/python3.7-experimental), I'd still like to get to the bottom of this.

Here's my guess:
All python versions>3.6 are compiled with gcc, and building wheels from source (like with numpy) would require your computer to have gcc installed. I got past this on a mac with `brew install gcc`. For Windows I couldn't tell you, try [this](https://www.guru99.com/c-gcc-install.html). I believe running `pip install <your-pkgs-here> --no-cache-dir` after installing gcc *should* work.
I'll have access to a windows machine by tomorrow so I can start actively debugging then.

**Comment by shreyasingh1** [comment]
I tried the gcc installation instructions above, and then followed the link [here](https://stackoverflow.com/questions/3297254/how-to-use-mingws-gcc-compiler-when-installing-python-package-using-pip) (about how to use the gcc compiler when installing with pip) to make a disutils.cfg file within my conda environment path.  Unfortunately, running `pip install -e . --no-cache-dir` is throwing the same error listed above for me

**Comment by bvarjavand** [comment]
I have a few other hunches (double check PATH via ‘which gcc’, and adding microsoft manifest tool to the path). I’ll test them on a PC tomorrow.

**Comment by bvarjavand** [comment]
I tried everything on a pc (windows10) from scratch via virtualenv in powershell. Installed and run with no issues. I have a few more guesses I scrounged up. One is the [microsoft manifest tool](https://docs.microsoft.com/en-us/windows/win32/sbscs/mt-exe) being added to PATH. It looks like Windows compiles wheels using this post python3.6.

**Comment by bvarjavand** [comment]
If the above still doesn't work, you can download the wheels you need directly, which will definitely not give the same error as you wont build any wheels.

**Comment by tathey1** [comment]
works now
