### ISSUE TITLE
Import errors after updating Python to 3.8.5

### ISSUE THREAD

**Issue by TanchyKing** [neurodata/brainlit#126]
It was fine when I was using 3.7.1. After I updated Python to 3.8.5, there are two errors occurring when I import step 1 modules. 

`ModuleNotFoundError: No module named '_SimpleITK'` occurs when importing modules related to brainlit and `ModuleNotFoundError: No module named 'vispy.visuals.text._sdf_cpu'` occurs when importing module napari. I don't think these codes are compatible with the newest version of Python on Windows.

**Comment by bvarjavand** [comment]
Agreed to some extent. See #124
