### ISSUE TITLE
Update README to address brainlit installation errors

### ISSUE THREAD

**Issue by shreyasingh1** [neurodata/brainlit#128]
Update the [README](https://github.com/neurodata/brainlit#installation) with any issues faced during brainlit installation and running the [tutorial notebook](https://github.com/neurodata/brainlit/blob/documentation/docs/notebooks/utils/downloading_brains.ipynb).  This could include but is not limited to:
- Specifying separate installation sections for Macs, Windows, and Unix systems
- Specifying compatible python versions and package versions
- Listing common error messages and their workarounds
- Listing commands to run and their expected outputs, so someone can confirm they have correctly installed brainlit
- Specifying how to create the cloudvolume aws permissions file
- Updating the [Visualize](https://github.com/neurodata/brainlit#visualize) section of the README, which refers to 'screenshots,' that don't render correctly.

**Comment by johnduva** [comment]
thanks for creating this Issue, Shreya. Heres a [link](https://docs.google.com/document/d/1h1NILKflZUMaG4bHzm9DcPOu7OhVwFBt1VnWcJFHYQk/edit?usp=sharing) to my notes for errors/workarounds that I encountered/handled on iOS. I think we should all post our notes on this Issue and then work together to combine them into the README

**Comment by tathey1** [comment]
done https://github.com/neurodata/brainlit/tree/develop/docs
