### ISSUE TITLE
README update: brainlit installation steps and navigation on the WSL2 Subsystem

### ISSUE THREAD

**Issue by shreyasingh1** [neurodata/brainlit#131]
For windows users that would prefer to install and run brainlit on a unix system without the speed sacrifice that comes with a full virtual machine, [installing on the Windows Linux Subsystem 2](https://docs.microsoft.com/en-us/windows/wsl/install-win10) is an option. WSL2 is a fully functioning Linux kernel that allows you to run ELF64 Linux binaries on the Windows OS.  

I will update the readme to include (1) how to install WSL2 on a Windows 10 machine, (2) the steps to install and run brainlit on WSL2, and (3) the drawbacks of running brainlit on WSL2: most notably, configuring Jupyter Notebook to launch properly and the inability to launch the Napari viewer

**Comment by bvarjavand** [comment]
Looks like it's possible to view GUI elements via X11 port forwarding (though in my experience it's always a bit laggy). See [here](https://stackoverflow.com/questions/43397162/show-matplotlib-plots-and-other-gui-in-ubuntu-wsl1-wsl2).

**Comment by shreyasingh1** [comment]
Thanks, X11 port forwarding via the VcXsrv X-server ended up working, and GUI elements can now successfully be launched from WSL2! This also makes the process of configuring jupyter notebook launch much simpler. I'll detail the installation steps I took in the README update.  

Unfortunately Napari still doesn't fully launch (only launches a black screen), likely because WSL2 is quite new and doesn't support OpenGL versions>1.5 yet. ([thread specific to WSL2](https://discourse.ubuntu.com/t/opengl-on-ubuntu-on-wsl-2-timeline/17599)) ([General WSL/OpenGL thread](https://superuser.com/questions/1487555/how-to-troubleshoot-opengl-on-ubuntu-under-windows-10-wsl)) This should be fixed by Microsoft & Collabora in upcoming WSL2 updates.
