### ISSUE TITLE
mip=0 not working

### ISSUE THREAD

**Issue by johnduva** [neurodata/brainlit#154]
@bvarjavand and I determined that mip=0 did work as expected when calling NeuroglancerSession(). Had to switch to mip=1.

**Comment by tathey1** [comment]
at which s3 bucket?

**Comment by tathey1** [comment]
@johnduva - @bvarjavand tells me that this was not a an error in the code per se, but due to possibly unclear documentation. Is this true? How can we make the documentation more clear so someone else won't face this same issue?

**Comment by FelixChihTing** [comment]
While I was checking if the output of ```_get_voxel()``` is identical with the second output ```bbox``` of the ```pull_voxel()```, I found that when ```mip=1```, the two outputs will be different in length, but the rest of the array will be identical in values. Also, the ```bbox``` output of ```pull_voxel()``` tends to list fewer arrays than ```_get_voxel()```, e.g., for ```seg_id``` is looped in ```range(50)```, ```get_voxel()``` will give 14 arrays but ```pull_voxel()``` will only give 13; for ```seg_id``` is looped in ```range(1000)```, the former will give 180 arrays and the latter will give 177 arrays.
When ```mip=0``` and ```range(1000)```, the situation is similar, i.e., the former gives 180 arrays, and the latter gives 177 arrays.
However, when ```mip=2```, the outputs of ```get_voxel()``` and ```bbox``` from ```pull_voxel()``` will be identical, and both contain 180 arrays. Or if ```mip=0```, and ```range(100)```, the both functions will give identical arrays of 39 in length.

the script i'm using to test the difference is below:
```
import brainlit
from brainlit.utils.session import NeuroglancerSession
import numpy as np
from pathlib import Path
import pytest

dir = "s3://open-neurodata/brainlit/brain1"
dir_segments = "s3://open-neurodata/brainlit/brain1_segments"
mip = 0; radius = 150; v_id = 0
voxs = []
voxs2 = []
ngl_sess = NeuroglancerSession(mip=mip, url=dir, url_segments=dir_segments)
for seg_id in range(100):
    try:
        vox = ngl_sess._get_voxel(seg_id, v_id) 
        voxs.append(vox)
    except:
        pass

for seg_id in range(100):
    try:
        _,vox2,_ = ngl_sess.pull_voxel(seg_id, v_id)
        voxs2.append(np.array(np.floor(vox2.center()[:])))
    except:
        pass

np.testing.assert_array_equal(voxs,voxs2)
```

**Comment by johnduva** [comment]
@tathey1 to summarize the above, `pull_voxel()` does not work properly for mip=0 or 1, but does work for 2+. Is this intended? I don't understand your above comment about unclear documentation.

**Comment by tathey1** [comment]
Go ahead and look at some brain images, because there could be an issue if you are trying to pull data that is off of the side of the brain.

Then, can you isolate whether this is a code issue or a data issue?

**Comment by johnduva** [comment]
I was able to successfully run `pull_voxel()` with all mips while @FelixChihTing could not, so I suggested that he create a new environment and use the develop branch. This fixed his issue. I am closing this issue now since whatever the problem was has been fixed.
