### ISSUE TITLE
Upload benchmarking_data to openneurodata s3

### ISSUE THREAD

**Issue by tathey1** [neurodata/brainlit#156]
details to follow...

**Comment by shreyasingh1** [comment]
@tathey1 When trying to create a new folder in the mouse-light-viz bucket via the upload button on the website, I get a permissions error.  Is this something I can fix by uploading differently or with a permissions change, or would it be easier for someone with existing permissions to upload the benchmarking data?
![AWS s3 upload error message](https://user-images.githubusercontent.com/40285923/97064469-0c332480-1574-11eb-8143-d4d81d13e067.JPG)

**Comment by tathey1** [comment]
I just created that folder. And gave you more s3 permissions, so you should be good now.

**Comment by shreyasingh1** [comment]
@tathey1 I finished uploading the benchmarking data to S3, at the url s3://mouse-light-viz/benchmarking_data/.  Please take a look and let me know if I should change anything. If not, you can verify that it is done and close this issue.

**Comment by shreyasingh1** [comment]
Just realized that I haven't properly uploaded the info files - I'll work on finishing that and comment when it is complete.

**Comment by tathey1** [comment]
Here's some more details @shreyasingh1 

- Tif images and swc files should be converted to precomputed images/skeletons respectively
- Data should be uploaded to the open neurodata account
- Integrate (or at least link to) relevant documentation from our [lab website](https://neurodata.io/help/download/) - particularly the download and Annotate and Storage tabs

See [this notebook](https://github.com/neurodata/brainlit/blob/develop/docs/notebooks/utils/uploading_brains.ipynb) as reference for the first two bullets. @bvarjavand can be a source of info regarding this notebook since he wrote it.

**Comment by tathey1** [comment]
@shreyasingh1 if you find that the existing tutorials/notebooks in brainlit are not adequate in making it easy to upload/download data, I'd encourage making some new ones and, in addition to bullet 3 above, making a PR into brainlit that could be for sprint 1.

**Comment by shreyasingh1** [comment]
Associated PR: https://github.com/neurodata/brainlit/pull/182
- Made changes to upload.py, swc.py and session.py to automate upload and download of the benchmarking data
- Documented these workflows in two tutorial notebooks, upload_benchmarking.ipynb and download_benchmarking.ipynb

@tathey1, per the merged PR, can we close this issue?
