### ISSUE TITLE
Implement or Figure out how to compute SD, SSD metrics to compare swc files

### ISSUE THREAD

**Issue by tathey1** [neurodata/brainlit#162]
SD and SSD are metrics that evaluate how similar two neuron traces are. They are described in [Peng et. al. 2010](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2857929/)

**Comment by tathey1** [comment]
This could be a PR into networkx

**Comment by fxu10** [comment]
The V3D paper states that the functions are part of the V3D software, however the download link at the end of the paper is no longer valid. I tried looking for the function in Vaa3D instead, but could not find it.

There is a different function in Vaa3D under the plug-in neuron_utilities/neuron_distance which computes the "distance between two neurons. Distance is defined as the average distance among all nearest pairs in two neurons." I think this is potentially usable, but it does not directly match SD and SSD metrics.

**Comment by fxu10** [comment]
I was able to locate the source code, in a repository called 'v3d_external', listed under the Vaa3D repository, [here](https://github.com/Vaa3D/v3d_external/blob/master/v3d_main/neuron_editing/neuron_sim_scores.cpp).

**Comment by fxu10** [comment]
Updates:
According to [Dr. Peng's response to a forum post](https://www.nitrc.org/forum/message.php?msg_id=2866), the original functionality in V3D was a right-click option on the 3D viewer when loading 2 neurons together. I'm not sure if this is 2 labelsets or 2 neurons, or if it needs to be binarized. 

Additionally, when running APP2, there is an option to "automatically resample". This likely takes care of the resample-before-SSD issue we were running into earlier.

**Comment by tathey1** [comment]
addressed [here](https://github.com/neurodata/brainlit/pull/179)
