### ISSUE TITLE
https://brainlight.readthedocs.io/en/latest/

### ISSUE THREAD

**Issue by jovo** [neurodata/brainlit#163]
shouldn't that be brainlit, not brainlight?

**Comment by tathey1** [comment]
http://brainlit.neurodata.io/ should work now

**Comment by jovo** [comment]
cool, though i'd make this the homepage: http://brainlit.neurodata.io/readme

On Mon, Nov 16, 2020 at 4:11 PM Thomas Athey <notifications@github.com>
wrote:

>
> *      External Email - Use Caution      *
>
>
>
> Closed #163
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fneurodata%2Fbrainlit%2Fissues%2F163&data=04%7C01%7Cjovo%40jhu.edu%7C1d851035cad643a6882a08d88a746f29%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637411580518379350%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ijNBpYYLFSV0xFRSpA6pfu02dZNNrsJIRJg6bKHn12U%3D&reserved=0>
> .
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fneurodata%2Fbrainlit%2Fissues%2F163%23event-4002362500&data=04%7C01%7Cjovo%40jhu.edu%7C1d851035cad643a6882a08d88a746f29%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637411580518379350%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=QC92V1NnzYWPSDb9AJ9aVgCjuwLoeRhL4JTxKhoIA7Q%3D&reserved=0>,
> or unsubscribe
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAAKG4VH3VK7XSS4LV2VHTTSQGIR7ANCNFSM4TM46ZNQ&data=04%7C01%7Cjovo%40jhu.edu%7C1d851035cad643a6882a08d88a746f29%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637411580518389344%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=a%2FQ0khMJla9iNeSC3hgAsr9uC3FSQ7DhxhqStrgrWRo%3D&reserved=0>
> .
>


-- 
With gratitude,

Joshua T Vogelstein, PhD
neurodata.io | BME@JHU <https://www.bme.jhu.edu/> | dA/dt > 0 > dJ/dt
<https://twitter.com/neuro_data/status/1279067902658916352>
where A = appreciating, J = judging, and t = time.
How can I do better? <https://forms.gle/iEad8byD89eTPdYx6>
