### ISSUE TITLE
reduce codes associated with fit_spline

### ISSUE THREAD

**Issue by FelixChihTing** [neurodata/brainlit#170]
1. In the [notebook](https://github.com/NeuroDataDesign/brainlit/blob/develop/docs/notebooks/algorithms/view_swc_spline.ipynb), when calling for the swc file, it is doing a [recursive searching](https://github.com/NeuroDataDesign/brainlit/blob/develop/docs/notebooks/algorithms/view_swc_spline.ipynb?short_path=927559d#L60-L82), where a while loop and a file searching function are employed, in the local repository. This searching process is unnecessarily complicated. However, the path to the swc file is partially known, i.e., ```...\brainlit\data\data_octree```. The solution would be to locate the path to the known file, say the current notebook, and use it as the root to redirect the path to the swc file.
2. Currently, a few input format checks are required before using the ```fit_spline_tree_invariant``` function under the ```GeometricGraph```class, i.e., check if location of nodes are defined in ```loc``` attributes and is defined in 3D coordinates. By doing checking processes in the modified ```GeometricGraph```class, the ```fit_spline_tree_invariant``` can be more user-friendly. The modified ```GeometricGraph```class should be called [in this way](https://github.com/NeuroDataDesign/brainlit/pull/17) so as to save the [input format checking](https://github.com/NeuroDataDesign/brainlit/blob/develop/brainlit/algorithms/trace_analysis/fit_spline.py#L90-L102) process.

**Comment by tathey1** [comment]
addressed [here](https://github.com/neurodata/brainlit/pull/178)
