### ISSUE TITLE
Submit pull request adding nonlinear features functionality

### ISSUE THREAD

**Issue by bvarjavand** [neurodata/brainlit#18]
Submit a pull request to this repository which does the following things:

- [x] Develop a python script called `brainlit/preprocessing/features/nonlinear_features.py` which:
 1. pulls a region around a voxel
 2. computes activations of *new nonlinear filters* on the region
      - an MLP with sigmoid activation function, and softmax function on the last layer

These features would then be able to be used with a classifier (such as `brainlit/algorithms/regression/log_regression.py`) to predict axon vs not axon

- [x] Write tests for `brainlit/preprocessing/features/nonlinear_features.py` and document each method.

- [x] create a jupyter notebook in the documentation which demonstrates functionality visually and serves as a tutorial for other developers to trust and use the code

**Comment by sanika1201** [comment]
#29: Has the code for non-linear classifiers and all the neighborhoods generated are in the csv file and log_regression.py defines the classifiers.

#35 : Adds the tests for classification using the classifiers defined above for the generated neighborhoods.

#48 :  PR of updated notebooks and plots for single point intensity and 5x5x5 neighborhoods generated from with greater than 95% accuracy. The neighborhood generation issues from previous PR's were fixed.

The neighborhoods generated for above classification tasks were generated in this notebook which is not a part of the new feather pipeline:[https://nbviewer.jupyter.org/github/NeuroDataDesign/mouselit/blob/master/Sanika/neighborhood_extraction.ipynb](url)


#49 PR for classifiers tutorial using feather pipeline. Neighborhoods generated need fixing.
