### ISSUE TITLE
Find places to link to installation markdown files.

### ISSUE THREAD

**Issue by tathey1** [neurodata/brainlit#187]
There are several markdown files in this [directory](https://github.com/neurodata/brainlit/tree/develop/docs) that, as far as I'm aware, are not highlighted in our documentation. Let's find a place to link them to make sure that they can be found by people trying to install this package. The files I am referring to are: [1](https://github.com/neurodata/brainlit/blob/develop/docs/AWS_Credentials_Issues.md), [2](https://github.com/neurodata/brainlit/blob/develop/docs/Installation_on_Win7.md), and [3](https://github.com/neurodata/brainlit/blob/develop/docs/WSL2-install-instructions.md).

**Comment by Tobias2023** [comment]
Is this still available? When I go to the the [documentation](https://brainlit.readthedocs.io/en/latest/) there is a message that state the page doesn't exist. 

![image](https://user-images.githubusercontent.com/38087336/102809594-452f2000-4390-11eb-9aa7-bfc0ec13046c.png)

**Comment by tathey1** [comment]
Good point, I made [this issue](https://github.com/neurodata/brainlit/issues/191) regarding this. You can still see our documentation [here](https://brainlit.netlify.app/).

**Comment by tathey1** [comment]
looks like markdowns have been merged into [here](https://github.com/neurodata/brainlit/blob/develop/docs/install_faq.rst), but i am adding a header to the navigation bar [here](https://github.com/neurodata/brainlit/pull/361)
