### ISSUE TITLE
code and test running on separate brains

### ISSUE THREAD

**Issue by bvarjavand** [neurodata/brainlit#2]
Tasks for this semester: Automate process of uploading raw octree data and pulling back as a neuroglancer precomputed format to be segmented.

- [ ]  Create temporary s3 bucket for storing precomputed data format.
- [ ]  Pull both image and fragment data in an octree format(most likely from a cis computer) and upload as both neuroglancer precomputed onto the s3 bucket.
- Leverage code already in mouselight_code repo (swc2neuroglancer, upload_to_neuroglancer) for this task

- [ ]  Pull neuroglancer data from bucket to view and segment in napari.
Final DoD is a script for processing raw swc, image data into ngl_pipeline.py for visualization

**Comment by AF1111** [comment]
To elaborate:
End of semester goal should be to have a pipeline for:

- Pulling any brain image and skeleton data 
- Loading onto precomputed format for analysis
