### ISSUE TITLE
Test APP2 on images containing somas

### ISSUE THREAD

**Issue by fxu10** [neurodata/brainlit#212]
The benchmarking dataset contains images that are pieces of axons, where somas or cell bodies are not present. It is known that APP2 is marketed for single-neuron reconstructions, relying on images that likely have somas, so it follows that APP2 performance needs to be verified on mouselight images with somas.

Look into ground truth, do a one-way spatial distance test to see if the incomplete ground truth lines up with APP2 outputs.

**Comment by tathey1** [comment]
done [here](https://github.com/neurodata/brainlit/tree/develop/experiments/vaa3d_app2)
