### ISSUE TITLE
Simple Soma Detector

### ISSUE THREAD

**Issue by tathey1** [neurodata/brainlit#220]
I'd like to have a simple cell body detector based on morphological operations to serve as a baseline for cell detection.

**Comment by FelixChihTing** [comment]
@tathey1 does this issue repeats what @JacopoTeneggi is doing? or should be a simpler version?

**Comment by FelixChihTing** [comment]
@tathey1 does this issue repeats what @JacopoTeneggi is doing? or should be a simpler version?

**Comment by tathey1** [comment]
lets start simple, and as we develop, we can consult with Jacopo.

Start by thresholding, say, the top 5% intensity values, then [eroding](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.binary_erosion.html) 5 times and seeing if there are any remaining foreground voxels.
