### ISSUE TITLE
Adaptive Threshold test failing

### ISSUE THREAD

**Issue by tathey1** [neurodata/brainlit#244]
test_thres_from_gmm failed:
https://app.circleci.com/pipelines/github/neurodata/brainlit?branch=develop

**Comment by FelixChihTing** [comment]
The cause of the test failing is that ```test_thres_from_gmm``` generates random numbers each time. When the extreme values produced are exceeding the range between 0 and 255 (the depth of the 8-bit image), the image scale will be modified by the ```thres_from_gmm``` function. Therefore, I added two while loops to make sure the random numbers are within the range.
