### ISSUE TITLE
Cannot publish 0.3.0 to PyPI due to direct dependency

### ISSUE THREAD

**Issue by bvarjavand** [neurodata/brainlit#300]
The `brainlit-0.3.0` package has a direct dependency to `cloud-volume @ git+https://github.com/neurodata/cloud-volume.git@voxel-res-non-int` which PyPI does not allow for security reasons, I believe. See [discussion](https://github.com/pypa/pip/issues/6301) of the exact error message on a PyPI issue.

I think there are 2 solutions - one hacky and one legit. The hacky solution is to publish a fork of that cloudvolume branch on PyPI and reference our own release. The legit solution is to have cloudvolume incorporate the changes we need in that branch into their PyPI package, and then reference cloudvolume. There might be another way, I'm not sure.

For now people who want to use the most recent stable version of `brainlit` will need to clone the master branch and `pip install -e .`.

**Comment by dallen02** [comment]
- Updated dependencies in this pr
- Uploaded new version to [PyPI](https://pypi.org/project/brainlit/)
