### ISSUE TITLE
Add input types to function arguments

### ISSUE THREAD

**Issue by tathey1** [neurodata/brainlit#326]
As explained [here](https://stackoverflow.com/questions/2489669/how-do-python-functions-handle-the-types-of-the-parameters-that-you-pass-in), python lets you specify the data type of function arguments with "type hints." 

However these types will not raise errors if they are not satisfied. That is the second thing we should do.

**Comment by NipunGorantla** [comment]
Hello, I'd love to start working on this issue if no one is working on it yet!

**Comment by tathey1** [comment]
awesome! I dont think anyone else is working on this. Go ahead and fork this repo and then you could start working on it. Perhaps a good first file to work on is [this](https://github.com/neurodata/brainlit/blob/develop/brainlit/algorithms/generate_fragments/state_generation.py) one.

Then when you have made a couple changes you can open a pull request and we can use that PR to go back and forth with feedback/revisions etc.

Feel free to ask any clarifying questions in this thread.

**Comment by sejalsrivastava1** [comment]
I began adding type annotations to files in the algorithms and preprocessing directories -- what other directories/files need to be edited?

**Comment by tathey1** [comment]
@sejalsrivastava1 Let's aim for all the .py files in these submodules:
- algorithms
- feature_extraction
- napari_viterbrain
- preprocessing
- utils
- viz

**Comment by sejalsrivastava1** [comment]
Got it!
