### ISSUE TITLE
Ensure that 2018-08-01 traces (.swc's) are properly uploaded to S3 and align with image data

### ISSUE THREAD

**Issue by tathey1** [neurodata/brainlit#60]
Offset in current upload of the [data](https://viz.neurodata.io/?json_url=https://json.neurodata.io/v1?NGStateID=KgL6mPbLwFKGtw)

**Comment by bvarjavand** [comment]
The reason that the traces are not aligned is because of rounding errors when casting `float` to `int` on the Cloudvolume side. This can be solved by pulling Cloudvolume from our local fork `neurodata/cloud-volume`.

**Comment by bvarjavand** [comment]
did as described
