### ISSUE TITLE
Incorporate Registration in the brainlit documentation

### ISSUE THREAD

**Issue by bvarjavand** [neurodata/brainlit#65]
Brainlit uses `sphinx-autodoc` which makes documentation for the repo directly from method docstrings. 
 - The `registration` folder needs to be added to the list of subpackages [here](https://github.com/neurodata/brainlit/blob/develop/docs/reference/index.rst)
 - A file named `registration.rst` needs to be created in the same directly mimicking files like [algs.rst](https://github.com/neurodata/brainlit/blob/develop/docs/reference/algs.rst) such that
   * Each sub-subpackage (and so on) is included as a module
   * Each method and class from each module with appropriate docstrings is listed using `.. autoapifunction::` and `.. autoapiclass::`, respectively.

**Comment by FelixChihTing** [comment]
1. I found two registration folders: "brainlit/registration" and "brainlit/cloudreg/registration", which one should be added?
2. In the algs.rst, why only the methods and classes involved in the "adaptive_thresh.py" are included?
3. Also in the algs.rst, where does the "Regression" part come from?

**Comment by tathey1** [comment]
My understanding is that [this](https://github.com/neurodata/CloudReg) is the go-to place for cloudreg code.
