### ISSUE TITLE
enable the features folder in brainlight/preprocessing

### ISSUE THREAD

**Issue by bvarjavand** [neurodata/brainlit#8]
The features folder computes statistics on a volume to reduce dimensionality of the data our algorithms run on.
`brainlit/preprocessing/linear_features.py` converts a volume into a set of features based on different filter activations.
`brainlit/preprocessing/neighborhood.py` converts a volume into a set of features based on neighborhood-based algorithms.

Submit a Pull Request to the brainlit repository which makes the following changes:
- [x] modify `linear_features.py` to function on precomputed volumes using `brainlit` methods.
- [ ] test `linear_features.py` to validate output - including jupyter notebook tutorials to verify visually.
- [x] write docstrings for each method in `linear_features.py` which allow others to easily use the methods.

- [x] modify `neighborhood.py` to function on precomputed volumes using `brainlit` methods.
- [ ] test `neighborhood.py` to validate output - including jupyter notebook tutorials to verify visually.
- [x] write docstrings for each method in `neighborhood.py` which allow others to easily use the methods.

**Comment by mfigdore** [comment]
@bvarjavand PR demonstrating all algorithms in `features` function as expected through tests and add documentation.

**Comment by bvarjavand** [comment]
done
