### ISSUE TITLE
document and merge Fit splines to neurons code into develop branch

### ISSUE THREAD

**Issue by tathey1** [neurodata/brainlit#90]
Follow procedure in [this poster](https://neurodata.io/talks/mouselight/TDA4_Athey_Thomas_pdf.pdf)  to fit splines to neurons.

**Comment by jovo** [comment]
link to @tathey1 code here please

**Comment by tathey1** [comment]
https://github.com/neurodata/mouselight_code/blob/master/mouselight_code/src/make_connections.py

specifically fit_spline_tree_invariant function

I will add whoever works on this to the repo

**Comment by FelixChihTing** [comment]
@tathey1 the link is broken

**Comment by tathey1** [comment]
addressed [here](https://github.com/neurodata/brainlit/pull/167/files)
