### ISSUE TITLE
document and merge tommy's curvature and torsion of b-splines code into develop branch

### ISSUE THREAD

**Issue by tathey1** [neurodata/brainlit#91]
Curvature and torsion are computed via https://en.wikipedia.org/wiki/Torsion_of_a_curve

The derivatives of b-splines can be computed in closed form using B-splines (see e.g. Kunoth's book)

scipy represents splines with knots and orders, make a method to compute curvature and torsion of these splines.

**Comment by jovo** [comment]
link to tommy's branch?

**Comment by tathey1** [comment]
https://github.com/neurodata/mouselight_code/blob/master/mouselight_code/src/spline_fxns.py

I will share my repo with whoever works on this^

**Comment by JacopoTeneggi** [comment]
I am interested in working on this issue!

**Comment by tathey1** [comment]
Great, go ahead and check out the [Frenet-Frame](https://en.wikipedia.org/wiki/Frenet%E2%80%93Serret_formulas) to get an idea of what it is. [This page](https://en.wikipedia.org/wiki/Torsion_of_a_curve) gives the formula for torsion, and [here](https://en.wikipedia.org/wiki/Curvature#General_expressions) for curvature. You'll see that the formula for each just involves derivatives. Derivatives of b-splines can be computed in closed form (using Thm 3 of Kunoth's book on splines) or using [scipy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.splev.html).
